language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- wget http://apache.mirrors.tds.net/thrift/0.9.2/thrift-0.9.2.tar.gz -O thrift.tar.gz
- tar -xzf thrift.tar.gz
- cd thrift-0.9.2 && ./configure --prefix=/usr --without-ruby --without-python --without-c --without-erlang --without-go --without-nodejs && make && make install && cd  ..
install:
- travis_retry mvn clean install
after_success:
- mvn jacoco:report coveralls:report
- .travis_scripts/javadocs.sh
notifications:
  email:
    - corfudb-dev@googlegroups.com
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/e26458f01e3586e3c140
    on_success: always
    on_failure: always
    on_start: true
env:
  global:
    secure: WJZd15DtGSetu3HuaPE/Ap0EaPkR1D68ZUIFxyqUho8AY/rLGuANUrAY5U02jO1K1+iaYFMecRr2ZlOEK4N1XiBNz2gMnYmkHmUs9Gz+J3eA8SXdYOHsKyI5iRpyUgwzHIVLOKz03cvDlI04Rrm0Uhe/7hjNaXVge6I0YKPmiXI=
