---
# TravisCI Configuration
# This file is used by the TravisCI continuous integration platform
language: java
before_install:
    - sudo apt-get update -qq
    - wget http://apache.mirrors.tds.net/thrift/0.9.2/thrift-0.9.2.tar.gz -O thrift.tar.gz
    - tar -xzf thrift.tar.gz
    - cd thrift-0.9.2 && ./configure --prefix=/usr --without-ruby --without-python --without-c --without-erlang --without-go --without-nodejs && make && sudo make install
install:
    - which thrift
    - mvn clean install
script: mvn -e verify
