---
# CorfuDB configmaster sample configuration
#
# This simple configuration file spawns a simple configuration master
# on port 8002.
#
# Required:
# role (string) - org.corfudb.infrastructure.ConfigMasterService selects the configuration master
# port (number) - the port number to run on
#
# Optional:

role: org.corfudb.infrastructure.ConfigMasterService
port: 8002
pagesize: 4096
epoch: 0
sequencer:
    address: localhost
    port: 8000
layout:
    segments:
        - start: 0
          sealed: -1
          groups:
              - nodes:
                    - { address: localhost, port: 8001 }
          replicas: 1
