role: org.corfudb.infrastructure.ConfigMasterServer
port: 8002
pagesize: 4096
epoch: 0
sequencers:
  - "cdbsts://localhost:8000"
configmasters:
  - "cdbcm://localhost:8002"
layout:
  segments:
    - start: 0
      sealed: -1
      replicas: 1
      groups:
        - nodes:
          - "cdbslu://localhost:8001"
