role: org.corfudb.infrastructure.ConfigMasterServer
port: 9000
pagesize: 4096
epoch: 0
sequencers:
  - "nsss://localhost:8000"
configmasters:
  - "cdbcm://localhost:8002"
layout:
  segments:
    - replication: "cdbcr"
      start: 0
      sealed: -1
      replicas: 1
      groups:
        - nodes:
          - "nlu://localhost:8001"
