---
# CorfuDB configmaster sample configuration
#
# Goes with it_sequencer_2.yml and it_logunit_3.yml
#
# Required:
# role (string) - org.corfudb.infrastructure.ConfigMasterServer selects the configuration master
# port (number) - the port number to run on
#
# Optional:

role: org.corfudb.infrastructure.ConfigMasterServer
port: 12702
pagesize: 4096
epoch: 0
sequencers:
    - "cdbss://localhost:12601"
configmasters:
    - "cdbcm://localhost:12702"
layout:
    segments:
        - start: 0
          sealed: -1
          groups:
              - nodes:
                  - "cdbslu://localhost:12803"
          replicas: 1
