---
# CorfuDB configmaster sample configuration
#
# This simple configuration file spawns a simple configuration master
# on port 8002.
#
# Required:
# role (string) - org.corfudb.infrastructure.ConfigMasterServer selects the configuration master
# port (number) - the port number to run on
#
# Optional:

role: org.corfudb.infrastructure.ConfigMasterServer
port: 8005
pagesize: 4096
epoch: 0
sequencers:
    - "cdbsts://localhost:8003"
configmasters:
    - "cdbcm://localhost:8005"
remotelogs:
    - "cdbcm://localhost:8002"
    - "cdbcm://localhost:8005"
layout:
    segments:
        - start: 0
          sealed: -1
          groups:
              - nodes:
                  - "cdbslu://localhost:8004"
          replicas: 1
